FROM python:3.7

LABEL maintainer="contact@caleydo.org"
WORKDIR /phovea

# install dependencies last step such that everything before can be cached
COPY requirements*.txt docker_packages.txt docker_script*.sh _docker_data* ./
RUN (!(test -s docker_packages.txt) || (apt-get -y update && cat docker_packages.txt | xargs apt-get install -y)) && \
    pip install --no-cache-dir -r requirements.txt && \
    (pip install --no-cache-dir -r requirements_dev.txt)
RUN (!(test -s docker_script.sh) || bash ./docker_script.sh)

ENV PHOVEA_ENV=dev
ENV PHOVEA_SERVICE=api
ENV PHOVEA_CONFIG_PATH=config.json
# start phovea server from phovea_server repository root
CMD python phovea_server/__main__.py --use_reloader --env ${PHOVEA_ENV} ${PHOVEA_SERVICE}
EXPOSE 80
