FROM caleydo/phovea_python:v1.0-dev

MAINTAINER Samuel Gratzl <samuel.gratzl@datavisyn.io>
WORKDIR /phovea

# install dependencies last step such that everything before can be cached
COPY requirements*.txt docker_packages.txt docker_script*.sh _docker_data* ./
RUN (!(test -s docker_packages.txt) || (apt-get -y update && cat docker_packages.txt | xargs apt-get install -y)) && \
    pip install --no-cache-dir -r requirements.txt && \
    (pip install --no-cache-dir -r requirements_dev.txt)
RUN (!(test -s docker_script.sh) || bash ./docker_script.sh)

ENV PHOVEA_ENV=dev
ENV PHOVEA_SERVICE=api
ENV PHOVEA_CONFIG_PATH=config.json
#start ssh and service
CMD python phovea_server --use_reloader --env ${PHOVEA_ENV} ${PHOVEA_SERVICE}
EXPOSE 80
